### ISSUE TITLE
Multiple knife machines step on each other's toes

### ISSUE THREAD

**Issue by bossmc** [Metaswitch/chef#148]
We use `~/.chef/knife.rb` to hold deployment-wide configuration and, to get the information from there to the spun-up nodes we copy it into the attributes on the `clearwater-infrastructure` role.  Unfortunately, roles are global to the chef-server so, if two users do this with different `knife.rb` settings, they'll overwrite each other, leading to chaos (e.g. Ellis stops working, Restund stops accepting requests, password reminder emails are not sent).

The better way to do this is to store the deployment-wide configuration in a [databag](http://docs.getchef.com/data_bags.html) which can be set up per-deployment and is made available to the nodes automatically.

**Comment by rkd-msw** [comment]
I think we can actually do this more simply by putting signup_key and associated information in the environment - that doesn't need us to add a load of databag infrastructure and seems to just work. I'm doing that now.

**Comment by rkd-msw** [comment]
Fixed by https://github.com/Metaswitch/chef/pull/284.
