### ISSUE TITLE
Chronos doesn't start on AMI all-in-one images

### ISSUE THREAD

**Issue by mirw** [Metaswitch/chef#172]
Chronos never starts on AMI all-in-one images.  This is because the AMI all-in-one image build process uses chef, which creates an /etc/chronos/chronos.conf file containing the local IP address of the node on which the all-in-one image is being built, but nothing fixes this up on reboot.

**Comment by eleanor-merry** [comment]
Fixed in https://github.com/Metaswitch/chef/pull/194
