### ISSUE TITLE
Can't create a single box

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/chef#195]
I ran `knife box create -E rkd sprout`. The resulting box is corrupt:
* etcd_cluster is empty
* There's no /etc/clearwater/shared_config file

Creating single boxes is useful for testing infrastructure stuff (e.g. SNMP).

Andy, you know why this is happening (shared-config roles etc.), so assigning to you to comment.

**Comment by eleanor-merry** [comment]
I think the right fix here is to add a `--standalone` option when creating a single box. This will add the shared_config role to the box, and set the etcd_cluster value to the IP address of the box.
