### ISSUE TITLE
shared_config is not uploaded or applied after a deployment has been spun up

### ISSUE THREAD

**Issue by graemerobertson** [Metaswitch/chef#208]
E.g. add a Ralf node to an existing deployment (without a Ralf node). ralf_hostname gets correctly set in /etc/clearwater/config on sprout-1, but not on any other node. This is because it doesn't  get uploaded to etcd and applied on the other nodes. This problem exists for any changes to any environment variables.

Workaround is to run /usr/share/clearwater/clearwater-config-manager/scripts/upload_shared_config on sprout-1 (to upload the new config) and sudo /usr/share/clearwater/clearwater-config-manager/scripts/apply_shared_config on all the other nodes (to apply the new config).

@rkd-msw had some thoughts on the best way to fix this.

**Comment by rkd-msw** [comment]
Feels like we want a `knife update shared-config` command that runs chef-client/upload_shared_config/apply_shared_config as necessary (warning about service impaction).

**Comment by bossmc** [comment]
Pedantry: knife uses [noun] [verb] so it would be `knife shared config update` :grinning:

**Comment by eleanor-merry** [comment]
I'm going to add a 'knife shared config update' command that uploads all the config files on sprout-1, and runs apply_shared_config on all nodes. 

I'll also make it so that adding '--apply-shared-config' to a resize operation has the same effect
