### ISSUE TITLE
Can't deploy HSS using chef

### ISSUE THREAD

**Issue by mirw** [Metaswitch/chef#222]
If I try to deploy an HSS using chef (using `knife box create openimscorehss`), it fails.

This is because the `openimscorehss` role depends on `clearwater-infrastructure`, `clearwater-infrastructure` installs `clearwater-snmp-alarm-agent` and `clearwater-snmp-alarm-agent` depends on `/etc/clearwater/local_config`, but `/etc/clearwater/local_config` hasn't been created (because it's created by the `local_config` chef recipe, which isn't included in the `openimscorehss` role).

**Comment by mirw** [comment]
Fixing this would also fix https://github.com/Metaswitch/clearwater-snmp-handlers/issues/85.

**Comment by alango** [comment]
Deploying a cacti node runs into the same issue.
