### ISSUE TITLE
Creating an AMI would be better structured as a separate knife plugin

### ISSUE THREAD

**Issue by tim-hall** [Metaswitch/chef#43]
The current implementation of AMI creation puts the anonymizing of the machine instance mostly in the cw_ami recipe, but also puts the deletion of the chef keys in the auto-config init.d (can't delete chef's keys from within a recipe)

Better would be to have a separate "knife ami create -E <env>" type command that would separate out the anonymizing into a separate plugin which
-  could be used against any instance
-  would also be able to uninstall the chef client from the instance.

**Comment by eleanor-merry** [comment]
Closing this enhancement request as we're not focusing on this
