### ISSUE TITLE
chef-client needs to be nicer

### ISSUE THREAD

**Issue by mike-evans** [Metaswitch/chef#75]
Running chef client on a node that is under load can cause the node to tip over into overload because it hogs CPU while it is loading all the chef ruby classes.  This can be a big problem when scaling up a system under load when we run chef-client to reconfigure clustering, especially on crest nodes (Homestead and Homer).

We therefore need to run chef-client in some "niced" way, by nice on it's own didn't seem to cut it - I believe Andy has experiment and has a concrete proposal.

**Comment by rkd-msw** [comment]
@bossmc, am I right in thinking that the etcd work effectively resolves this, because we don't need to run `sudo chef-client` on existing nodes to recluster?

**Comment by bossmc** [comment]
Yes
